use_frameworks!

target 'YTPageController_Example' do
  pod 'YTPageController', :path => '../'
  pod 'BetterSegmentedControl'
  pod 'AKASegmentedControl'

  target 'YTPageController_Tests' do
    inherit! :search_paths

    
  end
end
